runtime: python39
entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 15s
  max_pending_latency: 15s
  max_instances: 1

handlers:
- url: /.*
  script: auto
